name: Splunk Packaging

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install splunk-packaging-toolkit-1.0.1.tar.gz

    - name: Validate Opsgenie Alert Action
      run: slim validate opsgenie_alert_action

  build:
    runs-on: ubuntu-20.04
    needs: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install splunk-packaging-toolkit-1.0.1.tar.gz

    - name: Extract version from app.conf
      id: extract-version
      run: |
        VERSION=$(grep -Po '(?<=^version = ).*' opsgenie_alert_action/default/app.conf)
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

    - name: Package Opsgenie Alert Action
      run: |
        slim package opsgenie_alert_action
        mv opsgenie_alert_action.tar.gz opsgenie_alert_action-${{ env.VERSION }}.tar.gz

    - name: Create release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ env.VERSION }}
        release_name: "Release v${{ env.VERSION }}"
        body: "Release of version ${{ env.VERSION }}."
        draft: false
        prerelease: false
        generate_release_notes: true
        files: opsgenie_alert_action-${{ env.VERSION }}.tar.gz
